name: Scraper Lomba Otomatis

on:
  schedule:
    - cron: '0 17 * * *'   # 17:00 UTC = 00:00 WIB
  workflow_dispatch:      

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install chromium && playwright install-deps
        
      - name: Run scraper to MongoDB
        env:
          IG_SESSION_ID: ${{ secrets.IG_SESSION_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python scraper.py
